

> Import libraries to use



In [1]:
import numpy as np

>  # Introduction to numpy (Skip if you already are familiar)

>> Creating a 1D array

In [ ]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


>> Creating a 2D array


In [ ]:
a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


>> Creating an array full of zeros


In [ ]:
a = np.zeros(shape=(10))
print(a)
a = np.zeros(shape=(5,2))
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


>> Infinity in numpy

In [ ]:
print(np.inf)

inf


>> Max and Argmax

In [ ]:
a = np.array([2,1,4,3])
print(np.max(a))
print(np.argmax(a))

4
2


>> From list to Numpy

In [ ]:
l = [1,2,3,4]
print(l)
print(np.asarray(l))

[1, 2, 3, 4]
[1 2 3 4]


>> Random in numpy

In [ ]:
# Array of Random integers ranging from 1 to 10 (with any size you want)
a = np.random.randint(low=1, high=10, size=(5,2))
print(a)

# Array of random elements of a list with any size you want
a = np.random.choice([0,1,2], size=(2,))

[[6 4]
 [1 6]
 [7 5]
 [5 9]
 [4 2]]


>> Shapes in numpy

In [ ]:
a = np.random.randint(low=1, high=5, size=(4,2))
print(a.shape)
print(a)

# Reshape a to a vector of shape = (8,1)
a = a.reshape((8,1))
print(a.shape)
print(a)

(4, 2)
[[1 3]
 [2 4]
 [4 4]
 [4 4]]
(8, 1)
[[1]
 [3]
 [2]
 [4]
 [4]
 [4]
 [4]
 [4]]


# Pre-defined utilities

In [7]:

int_to_char = {
    0 : 'u',
    1 : 'r',
    2 : 'd',
    3 : 'l'
}

policy_one_step_look_ahead = {
    0 : [-1,0],
    1 : [0,1],
    2 : [1,0],
    3 : [0,-1]
}

def policy_int_to_char(pi,n):

    pi_char = ['']

    for i in range(n):
        for j in range(n):

            if i == 0 and j == 0 or i == n-1 and j == n-1:

                continue

            pi_char.append(int_to_char[pi[i,j]])

    pi_char.append('')

    return np.asarray(pi_char).reshape(n,n)

# 1- Policy evaluation

In [39]:
from types import new_class
def policy_evaluation(n, pi, v, Gamma, threshhold):
    """
    This function should return the value function that follows the policy pi.
    Use the stopping criteria given in the problem statement.
    """
    delta = 0
    new_v = v.copy()
    for i in range(n):
        for j in range(n):
            if (i == 0 and j == 0) or (i == n-1 and j == n-1):
                continue


            v_old = v[i, j]
            action = pi[i, j]

            next_i = i + policy_one_step_look_ahead[action][0]
            next_j = j + policy_one_step_look_ahead[action][1]
            if next_i < 0 or next_i >= n or next_j < 0 or next_j >= n:
                next_i, next_j = i, j

            # new_v value calculation
            reward = -1
            new_v[i, j] = reward + Gamma * v[next_i, next_j]
    return new_v

# 2- Policy improvement

In [32]:
def policy_improvement(n, pi, v, Gamma):
    """
    This function should return the new policy by acting in a greedy manner.
    The function should return as well a flag indicating if the output policy
    is the same as the input policy.

    Example:
      return new_pi, True if new_pi = pi for all states
      else return new_pi, False
    """
    new_pi = np.zeros_like(pi)
    stable = True
    for i in range(n):
        for j in range(n):

            if (i == 0 and j == 0) or (i == n-1 and j == n-1):
                continue

            current_action = pi[i, j]
            best_action = current_action
            best_value = v[i, j]

            for action in range(4):
                next_i, next_j = i + policy_one_step_look_ahead[action][0], j + policy_one_step_look_ahead[action][1]

                if next_i < 0 or next_i >= n or next_j < 0 or next_j >= n:
                    next_i, next_j = i, j

                potential_value = Gamma * v[next_i, next_j]

                if potential_value > best_value:
                    best_action = action
                    best_value = potential_value

            new_pi[i, j] = best_action

            # stable test
            if best_action != current_action:
                stable = False
    return new_pi, stable

# 3- Policy Initialization

In [17]:
def policy_initialization(n):
  """
  This function should return the initial random policy for all states.
  With uniform probabilities.
  """
  pi = np.zeros(shape=(n, n))

  # For all state
  for i in range(n):
    for j in range(n):
      # Skip goal and starting state
      if i == 0 and j == 0 or i == n - 1 and j == n - 1:
        continue
      # Select random action with uniform probilities
      pi[i, j] = int(np.random.choice([0, 1, 2, 3]))

  return pi

# 4- Policy Iteration algorithm

In [5]:
def policy_iteration(n,Gamma,threshhold):

    pi = policy_initialization(n=n)

    v = np.zeros(shape=(n,n))

    while True:

        v = policy_evaluation(n=n,v=v,pi=pi,threshhold=threshhold,Gamma=Gamma)

        pi , pi_stable = policy_improvement(n=n,pi=pi,v=v,Gamma=Gamma)

        if pi_stable:

            break

    return pi , v

# Main Code to Test

In [40]:
n = 4

Gamma = [0.8,0.9,1]

threshhold = 1e-4

for _gamma in Gamma:

    pi , v = policy_iteration(n=n,Gamma=_gamma,threshhold=threshhold)

    pi_char = policy_int_to_char(n=n,pi=pi)

    print()
    print("Gamma = ",_gamma)

    print()

    print(pi_char)

    print()
    print()

    print(v)



Gamma =  0.8

[['' 'l' 'l' 'd']
 ['u' 'u' 'u' 'd']
 ['u' 'u' 'r' 'd']
 ['u' 'r' 'r' '']]


[[ 0.   -1.   -1.8  -2.44]
 [-1.   -1.8  -2.44 -1.8 ]
 [-1.8  -2.44 -1.8  -1.  ]
 [-2.44 -1.8  -1.    0.  ]]

Gamma =  0.9

[['' 'l' 'l' 'd']
 ['u' 'u' 'u' 'd']
 ['u' 'u' 'r' 'd']
 ['u' 'r' 'r' '']]


[[ 0.   -1.   -1.9  -2.71]
 [-1.   -1.9  -2.71 -1.9 ]
 [-1.9  -2.71 -1.9  -1.  ]
 [-2.71 -1.9  -1.    0.  ]]

Gamma =  1

[['' 'l' 'l' 'd']
 ['u' 'u' 'u' 'd']
 ['u' 'u' 'r' 'd']
 ['u' 'r' 'r' '']]


[[ 0. -1. -2. -3.]
 [-1. -2. -3. -2.]
 [-2. -3. -2. -1.]
 [-3. -2. -1.  0.]]
